language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Gjxy1e64TAfNffONDUwroSBXmZE32KPmy99EWvoRkQb2w25FgCmRme3nmBinC63J6Hji+IeU05+mXGxips6AFFkBoRvmySVKqqzh1x2qWAbD3roGpkXdAfSUQA0z21T3xhZBNix7I8AM7g1B9KD6JRYVzKe1GpRHMxccYlke51UzraOKX/0EjeaNGcmbM/lJzJNV1yZnHkVmksU6S9g/NcJ2QPD8+Qe/E9rYXXGx9ZBB8yqQxUYGs8+meal/81n+jsXA1BO0PBMUf7DPWTd2bgeVTg+S04c2Z0EBZGC93Zp4DTc18HG2LUIK4vq9qF0cVG+B6XGQwL/V83B2VHZtPieBKlNCDkoHOwT0ZhfNqm4LHEBTDt+WI6Y//QsJECy7yHxjMsbw7B83+mMGphRxT++WPExvcb7IM+kpNG8z5rS3iHplN0rorE1NWxhzjV456vtz3GKm8D8W2B2BHuHbfek3sboDx1Vv85MEAAq5y+EKUVS41aJhzYnD2G7+ZpNG1Yove5cWT+EGlWnaZZGffZwXGH8kD7OpTpqod6ADZdo1TqCfVJxSfZWWRYfH1ddTYS6tHTmkA4ctp40E6QM4M40YIv4MUpYygNKt30OoVVqjjgUrzbddQlIwvDjkwsxFe1b0S34zSODY9Vd6E5poupusm5wb6GiMYnvdVYhTV3I=
  app: blogAPI
  on:
    repo: DrCord/blogAPI
