language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: UWHA3Ejrt6MizJwZ3HN55odbjriAzMd7e5vkRvuLYtkcESPlHI2tMiPncSYGAurel1BlOi1z5hBIeaDnO+3Ak4X6ZUb9IfcoZBf2vdtWqUNe7O0b6+xJ9DR8bKOqeNsgNAbxahOjlS1pYmOgQ3odggM6JnsWvkKqIi37+W/ntpUgYyO3Iyz3NBCke/zB310Jq8kydOcmUWgVz7J+aNoekUyvcZrM3lxKHETqrq/a5/UlFNAntW4Odk1CAYDIURGIyopq7ythZD4oY65Ipgni6rgYLs032m4wOp5EzrRPAISTW0iqO7o/e1X8cdFbMn0V2mJrAmDma/h5IxqDy3wDE9z0OHfb91RtRcSYcJugdKgNan5QhsO3ugxbxdAuNLr3oOrcIJiNfvops2gCsmxuCDfBY/J5V+o1zvyKIBwAT2LTxX3yiYJJaBC9Tnpw2inl9BILXUff1ECoEbCgRVFYu9zsfOGQ/gpxMJqoaMWoUiPbsFfUd6CFd2RS0S6uFIopwdmxS59hxhH0gZDgXKxlrSpDyzDVMU9w/vcXlpQB2qotxHinndGhIbcjXf8t3nq1JFzlAv0mL5vIxF92Kd1rp4I76I3ucyeXg3SL6sNy45o6fraZdFD1Tz6XBN2DoeKT7knzwNGH9N7QWWFmk1K05A3nUMrYKv+jB/1tHkMO3qE=
  app: blogAPI
  on:
    repo: DrCord/blogAPI
